### ISSUE TITLE
If the reverse proxied server returns long content, it is cut off in the middle

### ISSUE THREAD

**Issue by shintaro-tanaka-precena** [acidlemon/mirage-ecs#69]
Thanks for a great library!
I found a behavior that may be a bug and I'm reporting it.

---

Environment
- Go: 1.22.2

It seems that if the reverse proxied server returns long content, it may get cut off in the middle.

We encountered the problem when returning a rather large static file (say about 100k bytes), such as a front-end task definition.

Here is how to reproduce it on the test code

```go
// transport_test.go
// Setup mock server
server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
	time.Sleep(tt.serverDelay)
	// Read some big file
	file, _ := os.ReadFile("./app.js")
	fmt.Println(len(file))
	w.Write(file)
}))
// ...
body, _ := io.ReadAll(resp.Body)
// Body size / File size are different values
fmt.Println(len(body))
```

For debugging, the following code was inserted into `reverseproxy.go:RoundTrip`, and it no longer reproduces the problem.

```go
// reverseproxy.go
func (t *Transport) RoundTrip(req *http.Request) (*http.Response, error) {
	// ...
	defer cancel()
	resp, err := t.Transport.RoundTrip(req.WithContext(ctx))
	if err == nil {
		body, err2 := io.ReadAll(resp.Body)
		if err2 != nil {
			return nil, err2
		}
		defer resp.Body.Close()

		log.Printf("Response Body: %s", body)
		slog.Warn(f("WITHOUT_TIMEOUT: code: %d\tlen: %s\n", resp.StatusCode, body))

		resp.Body = io.NopCloser(bytes.NewBuffer(body))
		return resp, nil
	}
```

Is this a bug or is there some workaround?

**Comment by fujiwara** [comment]
@shintaro-tanaka-precena Hi!

I think `w.Write()` does not guarantee writing all the contents successfully at once. See also https://pkg.go.dev/io#Writer

To separate a problem, please fix your code using `io.Copy` as below or use http.FileServer.

```go
server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
	time.Sleep(tt.serverDelay)
	file, err := os.Open("./app.js")
	if err != nil {
		panic(err)
	}
	if _, err := io.Copy(w, file); err != nil {
		panic(err)
	}
}
}))
```

**Comment by shintaro-tanaka-precena** [comment]
@fujiwara Thank you for your reply!

I see that `w.Write()` does not guarantee success.

So I tried rewriting the test code to the `io.Copy` code as you suggested.
```go
server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
	time.Sleep(tt.serverDelay)
	file, _ := os.Open("./_app.js")
	fileStat, _ := file.Stat()
	fmt.Println("fileSize:", fileStat.Size())
	if _, err := io.Copy(w, file); err != nil {
		panic(err)
	}
}))
// ...
fmt.Println("bodySize:", len(body))
```

Result, it was that `fileSize` and `bodySize` were not the same.
```sh
filesize: 82072
bodySize: 24438
```

So I think it is not a problem in the test code, `reverseproxy.go#RoundTrip` func cannot return all of the body.

**Comment by fujiwara** [comment]
@shintaro-tanaka-precena Thank you for the details! I confirmed it and found a problem in Trasnport.RoundTrip(). #70 will solve this issue, please wait a little.

**Comment by fujiwara** [comment]
v2.0.5 released! https://github.com/acidlemon/mirage-ecs/releases/tag/v2.0.5

**Comment by shintaro-tanaka-precena** [comment]
@fujiwara Thank you for the quick solving!I'll try it.

**Comment by acidlemon** [comment]
I close this issue. If you have any other concerns, please feel free to reopen it. 😄
